"""Local SQLite or persistent PostgreSQL, with separate application schemas.

SQL stays parameterized. This adapter supports the application's small SQL
surface, not arbitrary SQLite SQL. Cloud errors never fall back to a local DB.
"""
import os
import re
import sqlite3
from contextlib import contextmanager
from pathlib import Path

SCHEMAS = {'paper': 'investpilot_paper', 'ai': 'investpilot_ai', 'auth': 'investpilot_auth'}
LOCKS = {'paper': 731001, 'ai': 731002, 'auth': 731003}
SCHEMAS['results'] = 'investpilot_results'
LOCKS['results'] = 731004
SCHEMAS['settings'] = 'investpilot_settings'
LOCKS['settings'] = 731005
SCHEMAS['ai_us'] = 'investpilot_ai_us'
LOCKS['ai_us'] = 731006
AUTO_TABLES = {'price_history', 'market_history', 'equity_marks'}


class Record(dict):
    def __getitem__(self, key):
        return list(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


def record_factory(cursor):
    names = [column.name for column in cursor.description or ()]
    return lambda values: Record(zip(names, values))


def postgres_sql(query):
    # Preserve quoted SQL strings/identifiers while translating bound markers.
    pieces = re.split(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\")", query)
    return ''.join(piece.replace('?', '%s') if i % 2 == 0 else piece
                   for i, piece in enumerate(pieces))


class Connection:
    def __init__(self, connection, remote, schema):
        self.connection, self.remote, self.schema = connection, remote, schema

    def execute(self, query, parameters=()):
        if self.remote:
            if query.strip().upper() == 'BEGIN IMMEDIATE':
                # Every remote context already holds the schema transaction lock.
                return None
            query = postgres_sql(query)
        return self.connection.execute(query, parameters)

    def executescript(self, script):
        if not self.remote:
            return self.connection.executescript(script)
        for statement in script.split(';'):
            statement = statement.strip()
            if not statement:
                continue
            # SQLite INTEGER PK generates IDs only for these history tables.
            match = re.match(r'CREATE TABLE IF NOT EXISTS (\w+)', statement, re.I)
            statement = re.sub(r'\bINTEGER\b', 'BIGINT', statement, flags=re.I)
            statement = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', statement, flags=re.I)
            if match and match[1] in AUTO_TABLES:
                statement = statement.replace('id BIGINT PRIMARY KEY',
                    'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            self.execute(statement)

    def has_column(self, table, column):
        if self.remote:
            return self.execute('SELECT 1 FROM information_schema.columns WHERE table_schema=? AND table_name=? AND column_name=?',
                                (self.schema, table, column)).fetchone() is not None
        if table not in ('decisions','sessions'):
            raise ValueError('Unsupported schema inspection')
        return any(row['name'] == column for row in self.execute(f'PRAGMA table_info({table})'))


class Database:
    def __init__(self, path, namespace, database_url=None, tenant=None):
        self.path, self.namespace = str(path), namespace
        self.schema = SCHEMAS[namespace]
        if tenant:
            if namespace not in ('paper','ai','ai_us') or not re.fullmatch('[0-9a-f]{32}',tenant): raise ValueError('Invalid account storage identity')
            self.schema += '_u_'+tenant
        self.url = os.getenv('INVESTPILOT_DATABASE_URL', '') if database_url is None else database_url
        self.remote = bool(self.url)
        if self.remote:
            import psycopg
            from psycopg.conninfo import conninfo_to_dict
            if not self.url.startswith(('postgresql://', 'postgres://')):
                raise ValueError('Cloud database must be a PostgreSQL URL')
            info = conninfo_to_dict(self.url)
            if info.get('sslmode') not in ('require', 'verify-ca', 'verify-full') and info.get('host') not in ('127.0.0.1', 'localhost', '::1'):
                raise ValueError('Cloud database requires TLS (sslmode=require or verify-full)')
            self.driver = psycopg
            with self.driver.connect(self.url, connect_timeout=15) as connection:
                connection.execute('SELECT pg_advisory_xact_lock(%s)', (LOCKS[namespace],))
                # Schema names come only from the fixed map above.
                connection.execute(f'CREATE SCHEMA IF NOT EXISTS {self.schema}')
        else:
            Path(path).parent.mkdir(parents=True, exist_ok=True)

    @contextmanager
    def db(self):
        if self.remote:
            with self.driver.connect(self.url, connect_timeout=15, row_factory=record_factory) as connection:
                connection.execute("SET LOCAL statement_timeout = '20s'")
                connection.execute('SELECT pg_advisory_xact_lock(%s)', (LOCKS[self.namespace],))
                connection.execute(f'SET LOCAL search_path TO {self.schema}')
                yield Connection(connection, True, self.schema)
        else:
            connection = sqlite3.connect(self.path, timeout=15)
            connection.row_factory = sqlite3.Row
            try:
                with connection:
                    yield Connection(connection, False, self.schema)
            finally:
                connection.close()
